[manager]
show_hidden = true

[opener]
edit = [
	{ run = 'code "$@"', orphan = true },
]
play = [
	{ run = 'vlc "$@"', orphan = true },
]


[open]
prepend_rules = [
	{ name = "*.mp4", use = "play" },
]

[plugin]
prepend_previewers = [
	{ name = "*.parquet", run = "parquet" },
]